---
title: "Charakteristika respondentů"
output: html_notebook
---

```{r setup}
source(here::here("R","setup_dotaznik.R"), encoding = "UTF-8")
source(here::here("R","datasety_dotaznik.R"), encoding = "UTF-8")

```


```{r}
plots <- list()
```


```{r}
plots$odpovedi <- datasety_wide$pouzitelne %>% group_by(stav_vyplneni) %>% summarise(pocet = n()) %>%
  mutate(stav_vyplneni = factor(stav_vyplneni, levels = c("nedokoncil","dokoncil_kratsi", "rozpracoval_doplnek", "dokoncil_doplnek", "dokoncil_delsi"), labels = c("Nedokončil ale vyplnil aspoň něco", "Dokončil kratší a nepokračoval", "Dokončil kratší a nedokončil pokračování", "Dokončil kratší i pokračování", "Dokončil delší"))) %>%
  ggplot(aes(x = stav_vyplneni, y = pocet, label = pocet)) + geom_bar(stat = "identity") + 
  geom_text(aes(color = pocet > 50), y = 50, hjust = 0, family = "SKAUT", size = 6) + 
              coord_flip() + vodorovne_popisky_x + expand_limits(y = 1330) +
  scale_color_manual(values = c("white", revize_cols("dark_blue")), guide = FALSE) +
    theme(axis.title = element_blank(), axis.text.x = element_blank(),
          axis.ticks.x = element_blank(), axis.line.x = element_blank()) +
  plot_annotation("Počet vyplnění", subtitle = "Všichni")

plots$odpovedi
```

```{r}
plots$odpovedi_15_26 <- datasety_wide$pouzitelne %>%  filter(age >= 15, age <= 26) %>% group_by(stav_vyplneni) %>% summarise(pocet = n()) %>%
  mutate(stav_vyplneni = factor(stav_vyplneni, levels = c("nedokoncil","dokoncil_kratsi", "rozpracoval_doplnek", "dokoncil_doplnek", "dokoncil_delsi"), labels = c("Nedokončil ale vyplnil aspoň něco", "Dokončil kratší a nepokračoval", "Dokončil kratší a nedokončil pokračování", "Dokončil kratší i pokračování", "Dokončil delší"))) %>%
  ggplot(aes(x = stav_vyplneni, y = pocet, label = pocet)) + geom_bar(stat = "identity") + 
  geom_text(aes(color = pocet > 50), y = 50, hjust = 0, family = "SKAUT", size = 6) + 
              coord_flip() + vodorovne_popisky_x + expand_limits(y = 1330) +
  scale_color_manual(values = c("white", revize_cols("dark_blue")), guide = FALSE) +
    theme(axis.title = element_blank(), axis.text.x = element_blank(),
          axis.ticks.x = element_blank(), axis.line.x = element_blank()) +
  plot_annotation("Počet vyplnění", subtitle = "Jen 15-26")

plots$odpovedi_15_26

```

```{r}
podil_z_registrovanych_roveru <- nrow(hlavni_data) / 12924
podil_z_registrovanych_roveru
nrow(datasety_wide$pouzitelne %>% filter(dokoncil_hlavni))
```


```{r}
plots$pohlavi <- hlavni_data %>%
  group_by(sex) %>%
  summarise(n = n()) %>%
  mutate(sex_factor = factor(sex, levels = c("jinak_neuvedeno","muz", "zena"), labels = c("Je to jinak/nepřeji si uvést","Muž","Žena"))) %>%
  ggplot(aes(x = "", y = n, fill = sex_factor)) + geom_bar(stat = "identity") + coord_polar("y", start = 0) + scale_fill_manual("", values = revize_cols("darkest_fill","mid_fill","white")) + 
  geom_text(aes(y = sum(n) - n/2 - 65 - c(0, cumsum(n)[-length(n)]), 
            label = scales::percent(n/sum(n))), color = revize_cols("dark_blue"), x = 1, size=5, family = "Roboto", fontface = "bold") +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), axis.line = element_blank(),
        axis.title = element_blank()) +
  plot_annotation("Respondenti dle pohlaví")

plots$pohlavi
```

```{r}
plots$vek <- hlavni_data %>% group_by(age) %>% summarise(pocet = n()) %>% mutate(podil = pocet / sum(pocet)) %>%
  ggplot(aes(x = age, y = podil, label = scales::percent(podil, accuracy = 1))) + geom_bar(stat = "identity") + #geom_text(aes(y = 0.01), color = revize_cols("dark_blue"), size = 6 ) + 
  vodorovne_popisky_x + scale_y_continuous("Podíl", labels = scales::percent) + scale_x_continuous("Věk") + plot_annotation("Věkové rozložení respondentů")
plots$vek
```


```{r}
plots$zivotni_faze <- hlavni_data %>% plot_summary_mc(zivotni_faze, "Životní fáze")
plots$zivotni_faze
```

```{r}
plots$kategorie_respondenta <- plot_summary_mc(hlavni_data, kategorie_respondenta_full, "Roverská zkušenost")
plots$kategorie_respondenta
```

```{r}
source(here::here("R","data_registrace_jednotlivci.R"), encoding = "UTF-8")
data_skautis_jednotlivci_raw <- registrace_jednotlivci()
data_skautis_jednotlivci <- data_skautis_jednotlivci_raw %>%
  filter(Year == 2018) %>%
  select(Year, Person_PseudoID, vek, ID_Sex) %>% distinct() %>%
  mutate(sex = if_else(ID_Sex == "female", "zena", "muz"))
```

Porovnávám s registrací 2018 (novější nemám).

```{r}
reprezentativnost_vek <- function(data_skautis_, data_pruzkum_, min_vek = 15, max_vek = 26, additional_group = "Vše") {
  dle_veku_pruzkum <- data_pruzkum_ %>% mutate(vek = age) %>%
    filter(!is.na(vek), vek >= min_vek, vek <= max_vek) %>%
    group_by(vek, {{additional_group}}) %>%
    summarise(clenu = length(vek)) %>% ungroup() %>% 
    mutate(zdroj = "Průzkum", 
           group = {{additional_group}})
  
  dle_veku_skautis <-  data_skautis_ %>%
    filter(vek >= min_vek, vek <= max_vek) %>%
    group_by(vek, {{additional_group}}) %>%
    summarise(clenu = length(vek)) %>% 
    ungroup() %>%
    mutate(zdroj = "SkautIS", 
           group = {{additional_group}})
  
dle_veku <- rbind(dle_veku_pruzkum, dle_veku_skautis) 

celkem <- dle_veku %>% group_by(zdroj) %>% summarise(celkem_v_datech = sum(clenu))

dle_veku <- dle_veku %>%
  inner_join(celkem, by = c("zdroj" = "zdroj")) %>% 
  mutate(podil = clenu / celkem_v_datech)

confidence <- dle_veku %>% filter(zdroj == "Průzkum") %>%
  inner_join(
    dle_veku %>% filter(zdroj == "SkautIS") %>% 
      select(vek, podil, group) %>%
      rename(podil_skautis = podil)
      , 
    by = c("vek" = "vek", "group" = "group")) %>%
  mutate(
    conf_lower = qbinom(0.025, celkem_v_datech, podil_skautis) / celkem_v_datech,
    conf_upper = qbinom(0.975, celkem_v_datech, podil_skautis) / celkem_v_datech,
    zdroj = "SkautIS",
  )


dle_veku %>% 
  ggplot(aes(x=vek, y = podil, color = zdroj, fill = zdroj, group = zdroj )) + 
  geom_ribbon(data = confidence, aes(ymin = conf_lower, ymax = conf_upper), alpha = 0.2, color = "transparent") +
  geom_point() + geom_line() + scale_color_revize() + scale_fill_revize() + vodorovne_popisky_x +
  facet_wrap(~group)
}

plots$reprezentativnost_vek <- reprezentativnost_vek(data_skautis_jednotlivci, hlavni_data) + plot_annotation("Reprezentativnost průzkumu dle věku")

plots$reprezentativnost_vek

reprezentativnost_vek(data_skautis_jednotlivci, hlavni_data %>% filter(sex != "jinak_neuvedeno"), additional_group = sex) + plot_annotation("Reprezentativnost dle věku a pohlaví")

#plots$reprezentativnost_vek_pohlavi

```



TODO: reprezentativnost dle kraje

TODO: Je ostrý odpad lidí u vyplnění kompetencí?

```{r save_plots}
save_list_of_plots(plots,"charakteristika_respondentu")
```
