---
title: "První výsledky"
output: html_notebook
---

```{r setup}
source(here::here("R","setup_dotaznik.R"), encoding = "UTF-8")
source(here::here("R","datasety_dotaznik.R"), encoding = "UTF-8")

```

```{r}
cela_data <- datasety_wide$hlavni
#check_vysledky(cela_data)
```
```{r}
expanded <- datasety_long$hlavni
```


```{r}
dokonceno <- sum(!is.na(cela_data$ended.hlavni), na.rm = TRUE)
rozpracovano <- sum(!is.na(cela_data$kategorie_respondenta) & is.na(cela_data$ended.hlavni))
```

Dotazník dokončilo neuvěřitelných `r dokonceno` roverů a dalších `r rozpracovano` ho vyplnilo alespoň zčásti.

```{r}

cela_data_rs <- cela_data %>% filter(age >= 15, age <= 26) %>% mutate(
  byl_na_rs_kurzu = co_zazil %contains_word% "roversky_kurz",
           byl_na_kurzu = co_zazil %contains_word% "roversky_kurz"
                       | co_zazil %contains_word% "radcovsky_kurz"
                       | co_zazil %contains_word% "cekatelky"
                       | co_zazil %contains_word% "jiny_kurz"
                       | co_zazil %contains_word% "vudcovky")


```


```{r}
plots <- list() 
max(cela_data_rs$let_v_kmeni, na.rm = TRUE)
```

```{r}
plots$roky_ve_spolecenstvi <- cela_data_rs %>% filter(let_v_kmeni != 42) %>% ggplot(aes( x = let_v_kmeni)) + geom_histogram(binwidth = 1)
plots$roky_ve_spolecenstvi

```

```{r}
plots$spokojenost_rs <- cela_data %>% plot_summary_mc(spokojenost_clenstvim_v_rs, "Spokojenost s členstvím ve společenství")
plots$spokojenost_rs
```

```{r}
plots$spokojenost_junak <- cela_data %>% plot_summary_mc(spokojenost_s_fungovanim_v_junaku, "Spokojenost s fungováním v Junáku")
plots$spokojenost_junak
```

```{r}
plots$komunikace_existujici <- cela_data %>% plot_summary_mc(komunikacni_kanaly_existujici, "Kde bys nejraději sledoval informace o roveringu")
plots$komunikace_existujici
plots$komunikace_hypoteticke <- cela_data %>% plot_summary_mc(komunikacni_kanaly_hypoteticke, "Kde bys nejraději sledoval informace o roveringu")
plots$komunikace_hypoteticke
attributes(cela_data$komunikacni_kanaly_hypoteticke)
```


```{r}
plots$zivotni_faze <- cela_data %>% plot_summary_mc(zivotni_faze, "Životní fáze", title_hjust = 0.5)
plots$zivotni_faze
```

```{r}
plots$spokojenost_rs_program <- cela_data %>% plot_summary_mc(spokojenost_s_roverskym_programem, "Celkově spokojen s RS")
plots$spokojenost_rs_program
```
```{r, fig.width=12}
plots$role <- cela_data %>% plot_summary_mc(role_skauting, "Role ve skautingu")
plots$role
```


```{r}
plots$co_zazil <- cela_data %>% plot_summary_mc(co_zazil, "Co zažili ve skautingu")
plots$co_zazil
```

```{r}

plots$problemy_cleni <- cela_data %>% plot_summary_mc(problemy_roveringu, "Hlavní problémy roveringu - jen členi společenství", title_hjust = 1)

plots$problemy_cleni

```

```{r}
plots$problemy_necleni <- cela_data %>% plot_summary_mc(problemy_roveringu_stredisko, "Hlavní problémy roveringu - jen bez společenství", title_hjust = 1)

plots$problemy_necleni
```


```{r}
if(any(!is.na(cela_data$problemy_roveringu) && !is.na(cela_data$problemy_roveringu_stredisko))) {
  stop("Problemy nejsou unikatni")
}
plots$problemy_all <- cela_data %>% mutate(problemy_roveringu_all = if_else(!is.na(problemy_roveringu), problemy_roveringu, 
                                                  problemy_roveringu_stredisko)) %>%
  plot_summary_mc(problemy_roveringu_all, "Hlavní problémy roveringu", title_hjust = 1.5)

plots$problemy_all
```


```{r}
plots$co_zazil <- plot_summary_mc(cela_data, co_zazil)
plots$co_zazil
```

```{r}
plots$s_cim_spokojen <- plot_summary_mc(cela_data, s_cim_spokojen, title = "S čím jsi ve společenství spokojen")
plots$s_cim_spokojen



plots$s_cim_nespokojen <- plot_summary_mc(cela_data, s_cim_nespokojen, title = "S čím jsi ve společenství NEspokojen") 
plots$s_cim_nespokojen

```

```{r}
plots$sluzba <- plot_summary_mc(cela_data, sluzba, title = "Služba za poslední měsíc") 
plots$sluzba
```


```{r}
plots$oranizace_spolecenstvi <- plot_summary_mc(cela_data, organizace_spolecenstvi, title = "Organizace kmene")
plots$oranizace_spolecenstvi
```

```{r}
plots$vyroky_o_roveringu_zazil <- plot_summary_mc(cela_data, vyroky_o_roveringu_zazil, "Rovering, který jsem zažil 1") 
plots$vyroky_o_roveringu_zazil

plots$vyroky_o_roveringu_zazil_2 <- plot_summary_mc(cela_data, vyroky_o_roveringu_zazil_2, "Rovering, který jsem zažil 2") 
plots$vyroky_o_roveringu_zazil_2
```

```{r}
plots$vyroky_o_roveringu_stredisko <- plot_summary_mc(cela_data, vyroky_o_roveringu_stredisko)
plots$vyroky_o_roveringu_stredisko
```


```{r}
plots$fungovani_skautskeho_oddilu <- plot_summary_mc(cela_data, fungovani_skautskeho_oddilu, "Moje družina ve skautském věku") 
plots$fungovani_skautskeho_oddilu
```

```{r}
plots$vychovne_nastroje <- plot_summary_mc(cela_data, vychovne_nastroje, "Používáme tyto výchovné nástroje")
plots$vychovne_nastroje
```

```{r}
plots$co_pomaha_roveringu <- plot_summary_mc(cela_data, co_pomaha_roveringu)
plots$co_pomaha_roveringu

```

```{r}
plots$proc_neni_rover <- plot_summary_mc(cela_data, proc_neni_rover, "Proč jsem už nejsem v roverském společenství")
plots$proc_neni_rover

```

```{r}
plots$proc_nebyl_rover <- plot_summary_mc(cela_data, proc_nebyl_rover)
plots$proc_nebyl_rover

```

```{r}
plots$bez_zkusenosti_velke_akce <- plot_summary_mc(cela_data, bez_zkusenosti_velke_akce, "Účast na akcích (jen bez roverské zkušenosti)")
plots$bez_zkusenosti_velke_akce


```

```{r}
plots$spolecenstvi_registrace <- plot_summary_mc(cela_data, spolecenstvi_registrace)
plots$spolecenstvi_registrace


```

```{r}
plots$kategorie_respondenta <- plot_summary_mc(cela_data, kategorie_respondenta_full, "Roverská zkušenost")
plots$kategorie_respondenta


```




```{r}
plots$pocet_clenu_spolecenstvi <- plot_summary_mc(cela_data, pocet_clenu_spolecenstvi, order_by_podil = FALSE, invert_color_threshold =  0.03)
plots$pocet_clenu_spolecenstvi

```

```{r}
plots$frekvence_kratkych_akci <- plot_summary_mc(cela_data, frekvence_kratkych_akci, "Frekvence kratších akcí", order_by_podil = FALSE)
plots$frekvence_kratkych_akci

```
```{r}
plots$frekvence_vicedennich_akci <- plot_summary_mc(cela_data, frekvence_vicedennich_akci, "Frekvence vícedenních akcí", order_by_podil = FALSE)
plots$frekvence_vicedennich_akci

```
```{r}
plots$frekvence_velkych_akci <- plot_summary_mc(cela_data, frekvence_velkych_akci, "Frekvence velkých akcí", order_by_podil = FALSE)
plots$frekvence_velkych_akci

```
```{r}
plots$bez_zkusenosti_setkavam_se_s_vrstevniky <- plot_summary_mc(cela_data, bez_zkusenosti_setkavam_se_s_vrstevniky, "Setkávání s vrstevníky -  roveři mimo společenství", order_by_podil = FALSE, invert_color_threshold = 0.02)
plots$bez_zkusenosti_setkavam_se_s_vrstevniky

```

```{r}
plots$bez_zkusenosti_seberozvojovy_program <- plot_summary_mc(cela_data, bez_zkusenosti_seberozvojovy_program, "Seberozvojový program -  roveři mimo společenství", order_by_podil = FALSE, invert_color_threshold = 0.02)
plots$bez_zkusenosti_seberozvojovy_program

```

## Obrazky ke kompetencim

```{r}
plots$zvladam_celkem <- expanded %>% 
  filter(kategorie_kompetence == "zvladam", !is.na(kompetence_odpoved)) %>% ggplot(aes(x = kompetence_odpoved)) +
    geom_histogram(bins = 7) +
    scale_x_continuous(breaks = c(1,7), labels = c("Zcela nesouhlasím", "Zcela souhlasím")) +
    theme(axis.title = element_blank(), axis.line.y = element_blank(), axis.title.y = element_blank(), axis.ticks.y = element_blank(), axis.text.y = element_blank()) + ggtitle('Celkové rozložení odpovědí "Zvládám to velmi dobře"')

plots$zvladam_celkem
```

```{r}
plot_kategorie_kompetence <- function(expanded, kategorie, kategorie_popis) {
  expanded %>% 
    filter(kategorie_kompetence == kategorie, !is.na(kompetence_odpoved)) %>% ggplot(aes(x = kompetence_odpoved)) +
      geom_histogram(bins = 7) +
      scale_x_continuous(breaks = c(1,7), labels = c("Zcela nesouhlasím", "Zcela souhlasím")) +
      theme(axis.title = element_blank(), axis.line.y = element_blank(), axis.title.y = element_blank(), axis.ticks.y = element_blank(), axis.text.y = element_blank()) + ggtitle(paste0('Celkové rozložení odpovědí "', kategorie_popis,'"'))
}

plots$dulezite_celkem <- plot_kategorie_kompetence(expanded, "dulezite", popis_pro_plot(cela_data, "duchovni_zivot_dulezite"))
plots$dulezite_celkem
```

```{r}
plots$zvladam_celkem <- plot_kategorie_kompetence(expanded, "zvladam", popis_pro_plot(cela_data, "duchovni_zivot_zvladam"))
plots$zvladam_celkem

```

```{r}
plots$rozvijim_celkem <- plot_kategorie_kompetence(expanded, "rozvijim", popis_pro_plot(cela_data, "duchovni_zivot_rozvijim"))
plots$rozvijim_celkem

```

```{r}
plots$skauting_celkem <- plot_kategorie_kompetence(expanded, "skauting", popis_pro_plot(cela_data, "duchovni_zivot_skauting"))
plots$skauting_celkem

```

## Ulozit obrazky

```{r}
plot_dir <- here::here("local_data","plots_basic")
if(!dir.exists(plot_dir)) {
  dir.create(plot_dir, recursive = TRUE)
}
for(plot_name in names(plots)) {
  for(format in c(".svg",".wmf",".png")) {
    ggsave(paste0(plot_dir, "/", plot_name, format), plots[[plot_name]])
  }
}
```




## Je to pro mě důležité

```{r}
tabulka_kompetence <- function(expanded, kategorie) {
  expanded %>% filter(kategorie_kompetence == kategorie) %>%
    group_by(kompetence) %>%
    summarise(prumer = mean(kompetence_odpoved, na.rm = TRUE), pocet = sum(!is.na(kompetence_odpoved))) %>%
    arrange(desc(prumer))
}

tabulka_kompetence(expanded, "dulezite")
```

```{r}
histogram_kompetence <- function(expanded, kategorie) {
  expanded %>% filter(kategorie_kompetence == kategorie, !is.na(kompetence_odpoved)) %>%
    ggplot(aes(kompetence_odpoved)) +
      geom_histogram(binwidth = 1) + facet_wrap(~kompetence) +
      theme(strip.text = element_text(size = 8))
}

histogram_kompetence(expanded, "dulezite")
```

```{r}
plot_kompetence_by_age <- function(expanded, kategorie) {
  expanded %>% filter(kategorie_kompetence == kategorie, !is.na(kompetence_odpoved), age >= 15, age <= 26) %>%
    group_by(age, kompetence) %>%
    summarise(prumer = mean(kompetence_odpoved) ,
              sem = sd(kompetence_odpoved) / sqrt(n())
              ) %>%
    group_by(kompetence) %>%
    mutate(od_prumeru = prumer - mean(prumer), low = od_prumeru - 1.96 * sem, high = od_prumeru + 1.96 * sem) %>%
    ungroup() %>%
    ggplot(aes(x = age, y = od_prumeru, ymin = low, ymax = high)) +
      geom_ribbon(fill = midd_fill) +
      geom_line() + facet_wrap(~kompetence) +
      theme(strip.text = element_text(size = 8))
}

plot_kompetence_by_age_smooth <- function(expanded, kategorie) {
  expanded %>% filter(kategorie_kompetence == kategorie, !is.na(kompetence_odpoved), age >= 15, age <= 26) %>%
    group_by(kompetence) %>%
    mutate(od_prumeru = kompetence_odpoved - mean(kompetence_odpoved)) %>%
    ggplot(aes(x = age, y = od_prumeru)) +
      geom_smooth() + facet_wrap(~kompetence) +
      theme(strip.text = element_text(size = 8)) 
}


plot_kompetence_by_age(expanded, "dulezite")
plot_kompetence_by_age_smooth(expanded, "dulezite")
```

## Zvládám to

```{r}
tabulka_kompetence(expanded, "zvladam")
```

```{r}
histogram_kompetence(expanded, "zvladam")
```


```{r}
plot_kompetence_by_age(expanded, "zvladam")
plot_kompetence_by_age_smooth(expanded, "zvladam")
```

## Rozvijim se v tom

```{r}
tabulka_kompetence(expanded, "rozvijim")
```

```{r}
histogram_kompetence(expanded, "rozvijim")
```

```{r}
plot_kompetence_by_age(expanded, "rozvijim")
plot_kompetence_by_age_smooth(expanded, "rozvijim")
```

## Skauting me rozviji

```{r}
tabulka_kompetence(expanded, "skauting")
```

```{r}
histogram_kompetence(expanded, "skauting")
```

```{r}
plot_kompetence_by_age(expanded, "skauting")
plot_kompetence_by_age_smooth(expanded, "skauting")
```

## Rozvijim se vs. skauting me rozviji

Všude číslo větší než 0 znamená, že "rozvíjím se" mělo vyšší hodnocení než "skauting mě v tom rozvíjí"

```{r}
rozdil_rozvijim_skauting <- expanded %>% select(session, kategorie_kompetence, kompetence_odpoved, kompetence) %>% filter(kategorie_kompetence %in% c("rozvijim","skauting")) %>%
  pivot_wider(id_cols = c("session", "kompetence"), names_from = kategorie_kompetence, values_from = kompetence_odpoved) %>%
  mutate(rozdil_rozvijim_skauting = rozvijim - skauting) %>%
  filter(!is.na(rozdil_rozvijim_skauting))


rozdil_rozvijim_skauting %>%
  group_by(kompetence) %>%
  summarise(prumer_rozdil = mean(rozdil_rozvijim_skauting, na.rm = TRUE), pocet = sum(!is.na(rozdil_rozvijim_skauting))) %>%
  arrange(desc(prumer_rozdil))


```

```{r}
rozdil_rozvijim_skauting %>%
  ggplot(aes(rozdil_rozvijim_skauting)) +
    geom_histogram(binwidth = 1) + facet_wrap(~kompetence) +
    geom_vline(xintercept = 0, color = "gray") +
    theme(strip.text = element_text(size = 8))
```

```{r}

```

