---
title: "Shrnutí kompetencí"
output: html_notebook
---


```{r setup}
source(here::here("R","setup_dotaznik.R"), encoding = "UTF-8")
source(here::here("R","datasety_dotaznik.R"), encoding = "UTF-8")
```


## Obrazky ke kompetencim

```{r}
plots$zvladam_celkem <- hlavni_data_long %>% 
  filter(kategorie_kompetence == "zvladam", !is.na(kompetence_odpoved)) %>% ggplot(aes(x = kompetence_odpoved)) +
    geom_histogram(bins = 7) +
    scale_x_continuous(breaks = c(1,7), labels = c("Zcela nesouhlasím", "Zcela souhlasím")) +
    theme(axis.title = element_blank(), axis.line.y = element_blank(), axis.title.y = element_blank(), axis.ticks.y = element_blank(), axis.text.y = element_blank()) + ggtitle('Celkové rozložení odpovědí \nZvládám to velmi dobře"')

plots$zvladam_celkem
```

```{r}
plot_kategorie_kompetence <- function(data_long, kategorie, kategorie_popis) {
  data_long %>% 
    filter(kategorie_kompetence == kategorie, !is.na(kompetence_odpoved)) %>% ggplot(aes(x = kompetence_odpoved)) +
      geom_histogram(bins = 7) +
      scale_x_continuous(breaks = c(1,7), labels = c("Zcela nesouhlasím", "Zcela souhlasím")) +
      theme(axis.title = element_blank(), axis.line.y = element_blank(), axis.title.y = element_blank(), axis.ticks.y = element_blank(), axis.text.y = element_blank()) + ggtitle(paste0('Celkové rozložení odpovědí "', kategorie_popis,'"'))
}


plots$dulezite_celkem <- plot_kategorie_kompetence(hlavni_data_long, "dulezite", popis_pro_plot(hlavni_data, "duchovni_zivot.dulezite"))
plots$dulezite_celkem
```

```{r}
plots$zvladam_celkem <- plot_kategorie_kompetence(hlavni_data_long, "zvladam", popis_pro_plot(hlavni_data, "duchovni_zivot.zvladam"))
plots$zvladam_celkem

```

```{r}
plots$rozvijim_celkem <- plot_kategorie_kompetence(hlavni_data_long, "rozvijim", popis_pro_plot(hlavni_data, "duchovni_zivot.rozvijim"))
plots$rozvijim_celkem

```

```{r}
plots$skauting_celkem <- plot_kategorie_kompetence(hlavni_data_long, "skauting", popis_pro_plot(hlavni_data, "duchovni_zivot.skauting"))
plots$skauting_celkem

```

## Ulozit obrazky

```{r}
plot_dir <- here::here("local_data","plots_basic")
if(!dir.exists(plot_dir)) {
  dir.create(plot_dir, recursive = TRUE)
}
for(plot_name in names(plots)) {
#  for(format in c(".svg",".wmf",".png")) {
  for(format in c(".png")) {
    ggsave(paste0(plot_dir, "/", plot_name, format), plots[[plot_name]], width = default_plot_width, height = default_plot_height)
  }
}
```




## Je to pro mě důležité



```{r}
tabulka_kompetence <- function(data_long, kategorie) {
  data_long %>% filter(kategorie_kompetence == kategorie) %>%
    group_by(kompetence) %>%
    summarise(prumer = mean(kompetence_odpoved, na.rm = TRUE), pocet = sum(!is.na(kompetence_odpoved))) %>%
    arrange(desc(prumer))
}

tabulka_kompetence(hlavni_data_long, "dulezite")
```

```{r}
histogram_kompetence <- function(data_long, kategorie) {
  data_long %>% filter(kategorie_kompetence == kategorie, !is.na(kompetence_odpoved)) %>%
    ggplot(aes(kompetence_odpoved)) +
      geom_histogram(binwidth = 1) + facet_wrap(~kompetence) +
      theme(strip.text = element_text(size = 8))
}

histogram_kompetence(hlavni_data_long, "dulezite")
```

```{r}
plot_kompetence_by_age <- function(data_long, kategorie) {
  data_long %>% filter(kategorie_kompetence == kategorie, !is.na(kompetence_odpoved), age >= 15, age <= 26) %>%
    group_by(age, kompetence) %>%
    summarise(prumer = mean(kompetence_odpoved) ,
              sem = sd(kompetence_odpoved) / sqrt(n())
              ) %>%
    group_by(kompetence) %>%
    mutate(od_prumeru = prumer - mean(prumer), low = od_prumeru - 1.96 * sem, high = od_prumeru + 1.96 * sem) %>%
    ungroup() %>%
    ggplot(aes(x = age, y = od_prumeru, ymin = low, ymax = high)) +
      geom_ribbon(fill = revize_cols("midd_fill")) +
      geom_line() + facet_wrap(~kompetence) +
      theme(strip.text = element_text(size = 8))
}

plot_kompetence_by_age_smooth <- function(data_long, kategorie) {
  data_long %>% filter(kategorie_kompetence == kategorie, !is.na(kompetence_odpoved), age >= 15, age <= 26) %>%
    group_by(kompetence) %>%
    mutate(od_prumeru = kompetence_odpoved - mean(kompetence_odpoved)) %>%
    ggplot(aes(x = age, y = od_prumeru)) +
      geom_smooth() + facet_wrap(~kompetence) +
      theme(strip.text = element_text(size = 8)) 
}


plot_kompetence_by_age(hlavni_data_long, "dulezite")
plot_kompetence_by_age_smooth(hlavni_data_long, "dulezite")
```

## Zvládám to

```{r}
tabulka_kompetence(hlavni_data_long, "zvladam")
```

```{r}
histogram_kompetence(hlavni_data_long, "zvladam")
```


```{r}
plot_kompetence_by_age(hlavni_data_long, "zvladam")
plot_kompetence_by_age_smooth(hlavni_data_long, "zvladam")
```

## Rozvijim se v tom

```{r}
tabulka_kompetence(hlavni_data_long, "rozvijim")
```

```{r}
histogram_kompetence(hlavni_data_long, "rozvijim")
```

```{r}
plot_kompetence_by_age(hlavni_data_long, "rozvijim")
plot_kompetence_by_age_smooth(hlavni_data_long, "rozvijim")
```

## Skauting me rozviji

```{r}
tabulka_kompetence(hlavni_data_long, "skauting")
```

```{r}
histogram_kompetence(hlavni_data_long, "skauting")
```

```{r}
plot_kompetence_by_age(hlavni_data_long, "skauting")
plot_kompetence_by_age_smooth(hlavni_data_long, "skauting")
```

## Rozvijim se vs. skauting me rozviji

Všude číslo větší než 0 znamená, že "rozvíjím se" mělo vyšší hodnocení než "skauting mě v tom rozvíjí"

```{r}
rozdil_rozvijim_skauting <- hlavni_data_long %>% select(session, kategorie_kompetence, kompetence_odpoved, kompetence) %>% filter(kategorie_kompetence %in% c("rozvijim","skauting")) %>%
  pivot_wider(id_cols = c("session", "kompetence"), names_from = kategorie_kompetence, values_from = kompetence_odpoved) %>%
  mutate(rozdil_rozvijim_skauting = rozvijim - skauting) %>%
  filter(!is.na(rozdil_rozvijim_skauting))


rozdil_rozvijim_skauting %>%
  group_by(kompetence) %>%
  summarise(prumer_rozdil = mean(rozdil_rozvijim_skauting, na.rm = TRUE), pocet = sum(!is.na(rozdil_rozvijim_skauting))) %>%
  arrange(desc(prumer_rozdil))


```

```{r}
rozdil_rozvijim_skauting %>%
  ggplot(aes(rozdil_rozvijim_skauting)) +
    geom_histogram(binwidth = 1) + facet_wrap(~kompetence) +
    geom_vline(xintercept = 0, color = "gray") +
    theme(strip.text = element_text(size = 8))
```

```{r}

```


