rm(list = ls())

library(tidyverse)

df <- readxl::read_excel("private_data/Sondy_Kolo_7_DATA_pro_Orla.xlsx", skip = 1)

glimpse(df)

df %>% 
  transmute(id, 
            q0_clen_junaka = `q0[1]`, 
         q0_vudce_oddilu = `q0[2]`,
         q0_ve_vedeni_oddilu = `q0[3]`,
         q0_vedouci_strediska = `q0[4]`,
         q0_predseda_kraje_okresu = `q0[5]`,
         q0_vychovny_zpravodej = `q0[6]`,
         q0_vudce_rs_kmene = `q0[7]`,
         q0_ani_jedna = `q0[8]`,
         vek = qs1Age,
         pohlavi = qs2Sex,
         velikost_obce = q3Size,
         kraj = q4Kraj,
         pocet_clenu_strediska = qs4StredSize,
         poc_oddilu = qs5StredOdd,
         pocet_obyvatel_kde_stredisko = qs6StredSize,
         pocet_clenu_v_oddile = qs7OddVel,
         v_oddile_benjaminci = `qs8OddVychKat[1]`,
         v_oddile_vlcata = `qs8OddVychKat[2]`,
         v_oddile_svetlusky = `qs8OddVychKat[3]`,
         v_oddile_skauti = `qs8OddVychKat[4]`,
         v_oddile_skautky = `qs8OddVychKat[5]`,
         v_oddile_roveri = `qs8OddVychKat[6]`,
         v_oddile_rangers = `qs8OddVychKat[7]`,
         funkce_v_oddile_zastupce_VO = `qs9OddFce[1]`,
         funkce_v_oddile_oddilovy_radce = `qs9OddFce[2]`,
         funkce_v_oddile_druzinovy_radce = `qs9OddFce[3]`,
         funkce_v_oddile_clen_vedeni_oddilu = `qs9OddFce[4]`,
         funkce_v_oddile_jine = `qs9OddFce[other]`,
         je_ve_meste_univezita = qRS1StredUniv,
         studium_ve_meste_strediska = qRS2Studium,
         pocet_obyvatel_kde_vetsina_roku = qRS3Size,
         realne_vedeni_oddilu = VOq1,
         kolik_let_vedeni = VOq2,
         pomoc_strediska_s_planovanim_cinnosti = `VOq3[1]`,
         pomoc_strediska_s_resenim_problemu = `VOq3[2]`,
         pomoc_strediska_s_radcovske_vzdelavani = `VOq3[3]`,
         pomoc_strediska_s_vzdelavani_na_miru = `VOq3[4]`,
         pomoc_strediska_s_pomoc_s_vyberem_vzdelavaci_akce = `VOq3[5]`,
         pomoc_strediska_s_podpora_prace_s_novym_vychovnym_programem = `VOq3[6]`,
         pomoc_strediska_s_poradanim_akci_pro_oddilovou_radu = `VOq3[7]`,
         pomoc_strediska_s_poradanim_stridskovych_akci = `VOq3[8]`,
         pomoc_strediska_s_tipy_na_cinnost = `VOq3[8]`,
         pomoc_strediska_dalsi = VOq4, 
         potreba_pomoci = VOq5,
         potreba_pomoci_real = VOq6A,
         potreba_pomoci_moznost = VOq6B,
         pomoc_od_real_vudce_oddilu = `VOq7A[1]`,
         pomoc_od_real_rada = `VOq7A[2]`,
         pomoc_od_real_vudce_jiny_oddil = `VOq7A[3]`,
         pomoc_od_real_vudce_strediska = `VOq7A[4]`,
         pomoc_od_real_byvaly_vudce_oddilu = `VOq7A[5]`,
         pomoc_od_real_byvaly_vudce_strediska = `VOq7A[6]`,
         pomoc_od_real_vychovny_zpravodaj_strediska = `VOq7A[7]`,
         pomoc_od_real_vychovny_zpravodaj_okresu = `VOq7A[8]`,
         pomoc_od_real_strediskova_rada = `VOq7A[9]`,
         pomoc_od_real_nekdo_jiny = `VOq7A[10]`,
         pomoc_od_moznost_vudce_oddilu = `VOq7B[1]`,
         pomoc_od_moznost_rada = `VOq7B[2]`,
         pomoc_od_moznost_vudce_jiny_oddil = `VOq7B[3]`,
         pomoc_od_moznost_vudce_strediska = `VOq7B[4]`,
         pomoc_od_moznost_byvaly_vudce_oddilu = `VOq7B[5]`,
         pomoc_od_moznost_byvaly_vudce_strediska = `VOq7B[6]`,
         pomoc_od_moznost_vychovny_zpravodaj_strediska = `VOq7B[7]`,
         pomoc_od_moznost_vychovny_zpravodaj_okresu = `VOq7B[8]`,
         pomoc_od_moznost_strediskova_rada = `VOq7B[9]`,
         pomoc_od_moznost_nekdo_jiny = `VOq7B[10]`,
         stredisko_zajistuje_planovani_cinnosti = `ZVOq2[1]`,
         stredisko_zajistuje_konkretni_vychovne_problemy = `ZVOq2[2]`,
         stredisko_zajistuje_radcovske_vzdelavani = `ZVOq2[3]`,
         stredisko_zajistuje_vzdelavani_na_miru = `ZVOq2[4]`,
         stredisko_zajistuje_pomoc_s_vyberem_vzdelavaci_akce = `ZVOq2[5]`,
         stredisko_zajistuje_podpora_prace_s_novym_programem = `ZVOq2[6]`,
         stredisko_zajistuje_vzdelavani_na_miru = `ZVOq2[7]`,
         stredisko_zajistuje_poradani_akci_pro_oddilovou_radu = `ZVOq2[8]`,
         stredisko_zajistuje_typy_na_cinnost = `ZVOq2[9]`,
         potreba_pomoci2 = ZVOq4,
         potreba_pomoci_real2 = ZVOq5A,
         potreba_pomoci_moznost2 = ZVOq5B,
         pomoc_od_real_vudce_oddilu2 = `ZVOq6A[1]`,
         pomoc_od_real_rada2 = `ZVOq6A[2]`,
         pomoc_od_real_vudce_jiny_oddil2 = `ZVOq6A[3]`,
         pomoc_od_real_vudce_strediska2 = `ZVOq6A[4]`,
         pomoc_od_real_byvaly_vudce_oddilu2 = `ZVOq6A[5]`,
         pomoc_od_real_byvaly_vudce_strediska2 = `ZVOq6A[6]`,
         pomoc_od_real_vychovny_zpravodaj_strediska2 = `ZVOq6A[7]`,
         pomoc_od_real_vychovny_zpravodaj_okresu2 = `ZVOq6A[8]`,
         pomoc_od_real_strediskova_rada2 = `ZVOq6A[9]`,
         pomoc_od_real_nekdo_jiny2 = `ZVOq6A[10]`,
         pomoc_od_moznost_vudce_oddilu2 = `ZVOq6B[1]`,
         pomoc_od_moznost_rada2 = `ZVOq6B[2]`,
         pomoc_od_moznost_vudce_jiny_oddil2 = `ZVOq6B[3]`,
         pomoc_od_moznost_vudce_strediska2 = `ZVOq6B[4]`,
         pomoc_od_moznost_byvaly_vudce_oddilu2 = `ZVOq6B[5]`,
         pomoc_od_moznost_byvaly_vudce_strediska2 = `ZVOq6B[6]`,
         pomoc_od_moznost_vychovny_zpravodaj_strediska2 = `ZVOq6B[7]`,
         pomoc_od_moznost_vychovny_zpravodaj_okresu2 = `ZVOq6B[8]`,
         pomoc_od_moznost_strediskova_rada2 = `ZVOq6B[9]`,
         pomoc_od_moznost_nekdo_jiny2 = `ZVOq6B[10]`,
         )


save(df, file = "private_data/sondy_180420.Rdata")
