---
title: "Stav roveringu"
output: html_notebook
---

```{r setup}
source(here::here("R","setup_dotaznik.R"), encoding = "UTF-8")
source(here::here("R","datasety_dotaznik.R"), encoding = "UTF-8")

```


```{r}
plots <- list() 
max(hlavni_data$let_v_kmeni, na.rm = TRUE)
```

```{r}
plots$roky_ve_spolecenstvi <- hlavni_data %>% filter(let_v_kmeni != 42) %>% ggplot(aes( x = let_v_kmeni)) + geom_histogram(binwidth = 1) + ggtitle("Počet let ve společenství") + scale_x_continuous("Let ve společenství") + scale_y_continuous("Počet")
plots$roky_ve_spolecenstvi

```

```{r}
plots$spokojenost_rs <- hlavni_data %>% plot_summary_mc(spokojenost_clenstvim_v_rs, "Spokojenost s členstvím ve společenství")
plots$spokojenost_rs
```

```{r}
plots$spokojenost_junak <- hlavni_data %>% plot_summary_mc(spokojenost_s_fungovanim_v_junaku, "Spokojenost s fungováním v Junáku")
plots$spokojenost_junak
```

```{r}
plots$komunikace_existujici <- hlavni_data %>% plot_summary_mc(komunikacni_kanaly_existujici, "Kde bys nejraději sledoval informace o roveringu")
plots$komunikace_existujici
plots$komunikace_hypoteticke <- hlavni_data %>% plot_summary_mc(komunikacni_kanaly_hypoteticke, "Kde bys nejraději sledoval informace o roveringu")
plots$komunikace_hypoteticke
attributes(hlavni_data$komunikacni_kanaly_hypoteticke)
```


```{r}
plots$zivotni_faze <- hlavni_data %>% plot_summary_mc(zivotni_faze, "Životní fáze", title_hjust = 0.5)
plots$zivotni_faze
```

```{r}
plots$role <- hlavni_data %>% plot_summary_mc(role_skauting, "Role ve skautingu")
plots$role
```


```{r}
plots$co_zazil <- hlavni_data %>% plot_summary_mc(co_zazil, "Co zažili ve skautingu")
plots$co_zazil
```

```{r}

plots$problemy_cleni <- hlavni_data %>% plot_summary_mc(problemy_roveringu, "Hlavní problémy roveringu - jen členi společenství", title_hjust = 1)

plots$problemy_cleni

```

```{r}
plots$problemy_necleni <- hlavni_data %>% plot_summary_mc(problemy_roveringu_stredisko, "Hlavní problémy roveringu - jen bez společenství", title_hjust = 1)

plots$problemy_necleni
```


```{r}
if(any(!is.na(hlavni_data$problemy_roveringu) && !is.na(hlavni_data$problemy_roveringu_stredisko))) {
  stop("Problemy nejsou unikatni")
}
plots$problemy_all <- hlavni_data %>% mutate(problemy_roveringu_all = if_else(!is.na(problemy_roveringu), problemy_roveringu, 
                                                  problemy_roveringu_stredisko)) %>%
  plot_summary_mc(problemy_roveringu_all, "Hlavní problémy roveringu", title_hjust = 1.5)

plots$problemy_all
```


```{r}
plots$co_zazil <- plot_summary_mc(hlavni_data, co_zazil)
plots$co_zazil
```

```{r}
plots$s_cim_spokojen <- plot_summary_mc(hlavni_data, s_cim_spokojen, title = "S čím jsi ve společenství spokojen")
plots$s_cim_spokojen



plots$s_cim_nespokojen <- plot_summary_mc(hlavni_data, s_cim_nespokojen, title = "S čím jsi ve společenství NEspokojen") 
plots$s_cim_nespokojen

```

```{r}
plots$sluzba <- plot_summary_mc(hlavni_data, sluzba, title = "Služba za poslední měsíc") 
plots$sluzba
```


```{r}
plots$oranizace_spolecenstvi <- plot_summary_mc(hlavni_data, organizace_spolecenstvi, title = "Organizace kmene")
plots$oranizace_spolecenstvi
```

```{r}
plots$vyroky_o_roveringu_zazil <- plot_summary_mc(hlavni_data, vyroky_o_roveringu_zazil, "Rovering, který jsem zažil 1") 
plots$vyroky_o_roveringu_zazil

plots$vyroky_o_roveringu_zazil_2 <- plot_summary_mc(hlavni_data, vyroky_o_roveringu_zazil_2, "Rovering, který jsem zažil 2") 
plots$vyroky_o_roveringu_zazil_2
```

```{r}
plots$vyroky_o_roveringu_stredisko <- plot_summary_mc(hlavni_data, vyroky_o_roveringu_stredisko)
plots$vyroky_o_roveringu_stredisko
```


```{r}
plots$fungovani_skautskeho_oddilu <- plot_summary_mc(hlavni_data, fungovani_skautskeho_oddilu, "Moje družina ve skautském věku") 
plots$fungovani_skautskeho_oddilu
```

```{r}
plots$vychovne_nastroje <- plot_summary_mc(hlavni_data, vychovne_nastroje, "Používáme tyto výchovné nástroje")
plots$vychovne_nastroje
```

```{r}
plots$co_pomaha_roveringu <- plot_summary_mc(hlavni_data, co_pomaha_roveringu)
plots$co_pomaha_roveringu

```

```{r}
plots$proc_neni_rover <- plot_summary_mc(hlavni_data, proc_neni_rover, "Proč jsem už nejsem v roverském společenství")
plots$proc_neni_rover

```

```{r}
plots$proc_nebyl_rover <- plot_summary_mc(hlavni_data, proc_nebyl_rover)
plots$proc_nebyl_rover

```

```{r}
plots$bez_zkusenosti_velke_akce <- plot_summary_mc(hlavni_data, bez_zkusenosti_velke_akce, "Účast na akcích (jen bez roverské zkušenosti)")
plots$bez_zkusenosti_velke_akce


```

```{r}
plots$spolecenstvi_registrace <- plot_summary_mc(hlavni_data, spolecenstvi_registrace)
plots$spolecenstvi_registrace


```

```{r}
plots$kategorie_respondenta <- plot_summary_mc(hlavni_data, kategorie_respondenta_full, "Roverská zkušenost")
plots$kategorie_respondenta


```




```{r}
plots$pocet_clenu_spolecenstvi <- plot_summary_mc(hlavni_data, pocet_clenu_spolecenstvi, order_by_podil = FALSE, invert_color_threshold =  0.03)
plots$pocet_clenu_spolecenstvi

```

```{r}
plots$frekvence_kratkych_akci <- plot_summary_mc(hlavni_data, frekvence_kratkych_akci, "Frekvence kratších akcí", order_by_podil = FALSE)
plots$frekvence_kratkych_akci

```
```{r}
plots$frekvence_vicedennich_akci <- plot_summary_mc(hlavni_data, frekvence_vicedennich_akci, "Frekvence vícedenních akcí", order_by_podil = FALSE)
plots$frekvence_vicedennich_akci

```
```{r}
plots$frekvence_velkych_akci <- plot_summary_mc(hlavni_data, frekvence_velkych_akci, "Frekvence velkých akcí", order_by_podil = FALSE)
plots$frekvence_velkych_akci

```
```{r}
plots$bez_zkusenosti_setkavam_se_s_vrstevniky <- plot_summary_mc(hlavni_data, bez_zkusenosti_setkavam_se_s_vrstevniky, "Setkávání s vrstevníky -  roveři mimo společenství", order_by_podil = FALSE, invert_color_threshold = 0.02)
plots$bez_zkusenosti_setkavam_se_s_vrstevniky

```

```{r}
plots$bez_zkusenosti_seberozvojovy_program <- plot_summary_mc(hlavni_data, bez_zkusenosti_seberozvojovy_program, "Seberozvojový program \n roveři mimo společenství", order_by_podil = FALSE, invert_color_threshold = 0.02)
plots$bez_zkusenosti_seberozvojovy_program

```

