---
title: "Analyza jinych odpovedi"
output: html_document
---

```{r setup}
if(!grepl("cz|utf", Sys.getlocale(), ignore.case = TRUE)) {
  Sys.setlocale(locale= 'English_United States.1250')
}
library(rlang)
library(lubridate)
library(tidyverse)
library(formr)
library(here)
library(RCzechia)
library(sf)
library(cowplot)
library(showtext)
library(polycor)

save_format <- ".svg"

theme_set(theme_cowplot(20))
dark_blue_color <- "#0040ae"
darkest_fill <- "#668cce"
midd_fill <- "#b2c5e6"
# theme_update(text = element_text(family = "Roboto", color = "white"), 
#              plot.background = element_rect(fill = dark_blue_color), 
#              line = element_line(color = "white"), 
#              rect = element_rect(color = "white"), 
#              axis.text = element_text(color = "white", face = "bold"), 
#              axis.title = element_text(color = "white"),
#              axis.line = element_line(color = "white"), axis.ticks = element_line(color = "white"),
#              strip.background = element_rect(color = "white", fill = darkest_fill))


#sysfonts::font_add_google("Roboto")
#sysfonts::font_add(family = "Skaut Bold", #paste0(Sys.getenv("APPDATA"),"/../Local/Microsoft/Windows/Fonts/skaut-bold-webfont.otf"))
#showtext_auto()

source(here::here("R","tools_dotaznik.R"), encoding = "UTF-8")

```

```{r}
cela_data_raw <- nacti_dotaznik()
cela_data <- cela_data_raw %>% vyfiltruj_pouzitelne() %>% preprocess_dat(verbose = FALSE) 
jine_odpovedi <- rbind(cela_data %>% filter(!is.na(komunikacni_kanaly_hypoteticke_jine)) %>% mutate(otazka="komunikacni_kanaly_hypoteticke") %>% select(otazka, text=komunikacni_kanaly_hypoteticke_jine),
cela_data %>% filter(!is.na(spolecenstvi_registrace_jine)) %>% mutate(otazka="spolecenstvi_registrace") %>% select(otazka,text=spolecenstvi_registrace_jine),
cela_data %>% filter(!is.na(vychovne_nastroje_jine)) %>% mutate(otazka="vychovne_nastroje") %>% select(otazka,text=vychovne_nastroje_jine),
cela_data %>% filter(!is.na(co_pomaha_roveringu_jine)) %>% mutate(otazka="co_pomaha_roveringu") %>% select(otazka,text=co_pomaha_roveringu_jine),
cela_data %>% filter(!is.na(proc_neni_rover_jine)) %>% mutate(otazka="proc_neni_rover") %>% select(otazka,text=proc_neni_rover_jine),
cela_data %>% filter(!is.na(otevrena)) %>% mutate(otazka="Celkova otevrena otazka") %>% select(otazka,text=otevrena))

write_csv2(jine_odpovedi,here("private_data","jine_odpovedi.csv"))

```