# Úvod k dalším kapitolám {#uvod}

Zásadní částí projektu byl velký průzkum mezi rovery, nechceme se ale omezit jen na tento samotný průzkum. 

- V kapitole \@ref(koncepce) - ["Děravá koncepce roveringu"](#koncepce) představujeme
obecnější závěry ke koncepci roveringu a roverského programu, které navazují na data volněji či se opírají primárně o úvahy a osobní zkušenosti
nás či dalších lidí, se kterými jsme v průběhu projektu o roveringu diskutovali. 
Tyto závěry nám osobně přijdou pro Junák důležitější než výstupy z dat, ale zase jsme si vědomi toho, 
že stojí na méně pevné půdě.

- V kapitolách \@ref(charakteristika-respondentu) - \@ref(kompetence) se věnujeme detailní analýze dat z velkého průzkumu. 
Začínáme [charakteristikou respondentů](#charakteristika-respondentu), 
pak se věnujeme první části dotazníku, která se dívala na [stav roveringu](#stav-roveringu) 
a končíme rozborem asi nejambicioznější části otázek, která se věnovala [kompetencím](#kompetence).

- Kapitole \@ref(odchody-lidi) se podíváme detailně na data z registrace o [odchodech členů](#odchody-lidi) s
hlavním důrazem na přechod ze skautského do roverského věku.

- Kapitola \@ref(sondy2015) se pak vrací k datům ze [sond do roveringu z roku 2015](#sondy2015), která nebyla dříve příliš využita. 


TODO: Odkazy na Drive na to, jak vypadal dotazník a další materiály.

_Kompletní kód všech analýz je k nalezení na https://github.com/martinmodrak/revize-rs _
