---
title: "Zivotni spokojenost"
output: html_document
---

```{r setup}
if(!grepl("cz|utf", Sys.getlocale(), ignore.case = TRUE)) {
  Sys.setlocale(locale= 'English_United States.1250')
}
library(rlang)
library(lubridate)
library(tidyverse)
library(formr)
library(here)
library(RCzechia)
library(sf)
library(cowplot)
library(showtext)
library(polycor)

save_format <- ".svg"

theme_set(theme_cowplot())
dark_blue_color <- "#0040ae"
darkest_fill <- "#668cce"
midd_fill <- "#b2c5e6"
# theme_update(text = element_text(family = "Roboto", color = "white"), 
#              plot.background = element_rect(fill = dark_blue_color), 
#              line = element_line(color = "white"), 
#              rect = element_rect(color = "white"), 
#              axis.text = element_text(color = "white", face = "bold"), 
#              axis.title = element_text(color = "white"),
#              axis.line = element_line(color = "white"), axis.ticks = element_line(color = "white"),
#              strip.background = element_rect(color = "white", fill = darkest_fill))


#sysfonts::font_add_google("Roboto")
#sysfonts::font_add(family = "Skaut Bold", #paste0(Sys.getenv("APPDATA"),"/../Local/Microsoft/Windows/Fonts/skaut-bold-webfont.otf"))
#showtext_auto()

source(here::here("R","tools_dotaznik.R"), encoding = "UTF-8")

```

```{r}
cela_data_raw <- nacti_dotaznik()
cela_data <- cela_data_raw %>% vyfiltruj_pouzitelne() %>% preprocess_dat(verbose = FALSE) 
check_vysledky(cela_data)
```

```{r zakladni lss analyzy}

cor.test(~let_v_junaku+lss,cela_data)
cor.test(~pocet_clenu_spolecenstvi+lss,cela_data)
cor.test(~frekvence_kratkych_akci+lss,cela_data)
cor.test(~frekvence_vicedennich_akci+lss,cela_data)
cor.test(~frekvence_velkych_akci+lss,cela_data)
cor.test(~spokojenost_s_roverskym_programem+lss,cela_data)

lss_pro_kategorie <- function(var) {
  cela_data %>% 
    group_by(!!var) %>% 
    summarize(m_lss = mean(lss, na.rm = T),sd_lss = sd(lss, na.rm = T), n = sum(!is.na(lss)) ,n_NA = sum(is.na(lss)))
}
lss_pro_kategorie(quo(kategorie_respondenta))

lss_pro_kategorie(quo(role_skauting))

lss_pro_kategorie(quo(zivotni_faze))
lss_pro_kategorie(quo(kraj))
lss_pro_kategorie(quo(sex))

```

```{r rozdelejless pro mc}

cela_data <- cela_data %>% rozsir_vsechna_mc()
cela_data %>% select(starts_with("roleFA_"),lss) %>% cor(use = "complete.obs") %>% knitr::kable(digits = 2)

n_roli <- rowSums(cela_data_role %>% select(starts_with("role_skauting_")) %>% as.matrix())

cela_data_role <- cela_data_role %>% 
  mutate(n_roli = n_roli)
cela_data_role %>% 
  group_by(n_roli) %>% 
  summarize(lss = mean(lss, na.rm = T), n =n()) %>% 
ggplot(aes(x=n_roli, y = lss, size = n)) + geom_point()

cela_data_role %>% 
  group_by(role_skauting_vedouci_roveru) %>% 
  summarize(m_lss = mean(lss, na.rm =T),
            sd_lss = sd(lss, na.rm =T),
            n = n())


cela_data_role %>% 
  group_by(role_skauting_vedouci_roveru) %>% 
  summarize(m_spoko = mean(spokojenost_s_roverskym_programem, na.rm =T),
            sd_spoko = sd(spokojenost_s_roverskym_programem, na.rm =T),
            n = n())

cela_data_role %>% 
  group_by(role_skauting_tahoun_roveru) %>% 
  summarize(m_spoko = mean(spokojenost_s_roverskym_programem, na.rm =T),
            sd_spoko = sd(spokojenost_s_roverskym_programem, na.rm =T),
            n = n())

cela_data_role %>% 
  group_by(role_skauting_tahoun_roveru) %>% 
  summarize(m_lss = mean(lss, na.rm =T),
            sd_lss = sd(lss, na.rm =T),
            n = n())

cela_data %>% select(starts_with("roleFA_"), lss) %>% cor(use = "complete.obs") %>% ggcorrplot::ggcorrplot(hc.order = T, type = "lower", lab =T)

t.test(spokojenost_s_roverskym_programem~role_skauting_vedouci_roveru,cela_data_role)
t.test(lss~role_skauting_vedouci_roveru,cela_data_role)


```

```{r rozdil kompetencni a lss}
expanded <- cela_data %>% expand_kompetence()

rozdil_dulezite_zvladam <- expanded %>% select(session, lss, kategorie_kompetence, kompetence_odpoved, kompetence) %>% filter(kategorie_kompetence %in% c("dulezite","zvladam")) %>%
  pivot_wider(id_cols = c("session", "kompetence", "lss"), names_from = kategorie_kompetence, values_from = kompetence_odpoved) %>%
  mutate(rozdil_dulezite_zvladam = dulezite - zvladam) %>%
  filter(!is.na(rozdil_dulezite_zvladam))

rozdil_dul_zvl_agg <- rozdil_dulezite_zvladam %>% 
  group_by(session) %>% 
  summarize(lss = mean(lss), rozdil_dulezite_zvladam = mean(rozdil_dulezite_zvladam)) 
rozdil_dul_zvl_agg %>% ggplot(aes(x = rozdil_dulezite_zvladam)) + geom_histogram()
rozdil_dul_zvl_agg %>% 
  cor.test(~lss+rozdil_dulezite_zvladam,.)

lss_cor <- expanded %>% select(session, lss, kategorie_kompetence, kompetence_odpoved, kompetence) %>% filter(kategorie_kompetence %in% c("dulezite","zvladam","rozvijim","skauting")) %>%
  pivot_wider(id_cols = c("session", "kompetence", "lss"), names_from = kategorie_kompetence, values_from = kompetence_odpoved) %>% 
  group_by(session) %>% 
  summarize(lss = mean(lss), 
            dulezite = mean(dulezite),
            zvladam = mean(zvladam),
            rozvijim = mean(rozvijim),
            skauting = mean(skauting)
            )
lss_cor %>% 
  select(lss, dulezite, zvladam, rozvijim, skauting) %>% 
  as.matrix() %>% 
  cor(use = "complete.obs") %>% knitr::kable(digits = 2)

cela_data %>% select(lss,ends_with("zvladam")) %>% as.matrix() %>% cor(use = "complete.obs") %>% round(2) %>% as_tibble(rownames = "var") %>% 
  select(var, lss) %>% arrange(-lss)

cela_data %>% select(lss,ends_with("rozvijim")) %>% as.matrix() %>% cor(use = "complete.obs") %>% round(2) %>% as_tibble(rownames = "var") %>% 
  select(var, lss) %>% arrange(-lss)

cela_data %>% select(lss,ends_with("dulezite")) %>% as.matrix() %>% cor(use = "complete.obs") %>% round(2) %>% as_tibble(rownames = "var") %>% 
  select(var, lss) %>% arrange(-lss)



```


```{r psc}
cela_data <- 
  cela_data %>% 
  mutate(reg_c_strediska = str_trim(reg_c_strediska)) %>% 
  mutate(reg_c_strediska_typ = 
           case_when(
             nchar(reg_c_strediska) == 8 ~ "ICO",
             str_detect(reg_c_strediska, "[:digit:]{2}[:alnum:]{1}\\.[:digit:]{2}") ~ "valid_reg_cis",
             str_detect(reg_c_strediska, "[:digit:]{3}\\.[:digit:]{2}") ~ "valid_reg_cis",
             str_detect(reg_c_strediska, "^[:digit:]{5}") ~ "cislo_bez_tecky_PSC",
             TRUE ~ NA_character_))
                       
xtabs(~reg_c_strediska_typ,cela_data)

psc_cr <- read_csv2(here::here("public_data/psc_okres_posta_utf8.csv")) %>% mutate(PSC = as.character(PSC))

psc_korektura <- cela_data %>% filter(reg_c_strediska_typ == "cislo_bez_tecky_PSC") %>% 
  mutate(regcislo_je_psc = reg_c_strediska %in% psc_cr$PSC) %>% 
  filter(!regcislo_je_psc) %>% 
  select(reg_c_strediska) %>% 
  rowwise() %>% 
  mutate(reg_c_spravne = psc_na_reg_cislo(reg_c_strediska))

write_csv2(psc_korektura,path = "public_data/psc_reg_cislo.csv")

eko_data <- readxl::read_excel(here::here("private_data/strediska_ico_ev_cislo.xlsx"))
eko_data$RegistrationNumber
ico_n_doplneni <- intersect(eko_data$IC %>% as.character() %>% unique(), cela_data$reg_c_strediska)

ico_reg_cislo <- eko_data %>% select(IC, RegistrationNumber) %>% 
  distinct() %>% 
  mutate(ic = as.character(IC)) %>% 
  filter(ic %in% ico_n_doplneni) %>% 
  filter(!is.na(ic))

write_csv(ico_reg_cislo,path = "public_data/ico_reg_cislo.csv")
```

## Roverske nastroje

```{r roverske nastroje faktorova analyza}
role_fa <- cela_data_role %>% select(starts_with("vychovne_nastroje_"))
role_fa <- sapply(role_fa, as.character)
het.mat <- hetcor(role_fa)$cor
het.mat %>% knitr::kable(digits = 2)

psych::fa.parallel(het.mat, n.obs = nrow(role_fa))

nastroje_fa_res <- psych::fa(het.mat, n.obs = nrow(role_fa), nfactors = 3, rotate = "varimax")
nastroje_fa_res
```

```{r roverske nastroje a spokojenost}

cr <- cela_data %>% select(starts_with("vychovne_nastroje_"),lss, spokojenost_s_roverskym_programem) %>% as.matrix() %>% Hmisc::rcorr() 
cr$r %>%   knitr::kable(digits = 2)
ggcorrplot::ggcorrplot(cr$r,hc.order = T, type = "lower", lab =T)
```


## Co pomaha roveringu

```{r}
cela_data %>% select(starts_with("co_pomaha")) %>% colnames()
xtabs(~co_pomaha_roveringu_financni_podpora+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~co_pomaha_roveringu_zpravodal+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~co_pomaha_roveringu_vyssi_mista+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~co_pomaha_roveringu_roversky_program+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~co_pomaha_roveringu_SI+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~co_pomaha_roveringu_akce_kratke+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~co_pomaha_roveringu_akce_dlouhe+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~co_pomaha_roveringu_neformalni_setkani+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~co_pomaha_roveringu_socialni_site+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)

```

Obecne lidem, co maji zkusenost s roveringem prijde, ze pomahaji neformalni setkani oproti tem, co nikdy ve spolecentstvi nebyli (ti veri na program). Je to tedy dost o vztazizch a neformalnich setkavani

## Problemy roveringu

```{r}
cela_data %>% select(starts_with("problemy")) %>% colnames()
xtabs(~problemy_roveringu_stredisko+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~problemy_roveringu_odstehovani+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~problemy_roveringu_nevidi_smysl+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~problemy_roveringu_spatne_vztahy+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~problemy_roveringu_bez_kvalitniho_programu+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~problemy_roveringu_bez_vedeni+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~problemy_roveringu_nevime_jak+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~problemy_roveringu_vytizeni_oddily+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~problemy_roveringu_vytizeni_mimo+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)
xtabs(~problemy_roveringu_pracovni_ceta+kategorie_respondenta, cela_data) %>% prop.table(margin = 2) %>% round(2)

```

## Faktorovka - co pomaha a co ne

```{r}
pomaha_skodi <- cela_data %>% select(starts_with("problemy_roveringu_"),-starts_with("problemy_roveringu_stredisko"),starts_with("co_pomaha_"),-co_pomaha_roveringu,-problemy_roveringu_stredisko)
psych::fa.parallel(pomaha_skodi)
fa_pomahaskodi <- psych::fa(pomaha_skodi,nfactors = 6, rotate = "varimax")
zobraz_fa(fa_pomahaskodi,nfac = 6,str_to_remove = "problemy_roveringu_") %>% knitr::kable()
```
